backend:
  name: git-gateway
  branch: main # O 'master', asegúrate de que sea el nombre de tu rama principal en GitHub

media_folder: "images" # Carpeta donde se guardarán las imágenes que subas
public_folder: "/images"

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - file: "index.html"
        label: "Página Principal"
        name: "index"
        fields:
          - { label: "Título Principal", name: "titulo", widget: "string" }
          - { label: "Descripción", name: "descripcion", widget: "text" }
